defaults: &defaults
  working_directory: ~/espresso
  docker:
    - image: circleci/node:8.9.4

version: 2
jobs:
  deploy:
    <<: *defaults

    steps:
      - checkout

      - run: 
          name: Write NPM Token to ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run:
          name: Set git config for NPM
          command: |
              git config user.email "bot@hillstreetlabs.com"
              git config user.name "Hill Street Labs Bot"

      - run: 
          name: Bump NPM version
          command: npm version patch -m "%s [skip ci]"

      - run:
          name: Publish to NPM
          command: npm publish

workflows:
  version: 2

  build:
    jobs:
      - deploy
